### ISSUE TITLE
additional help

### ISSUE THREAD

**Issue by zykoq** [matt-snider/dict.cc#13]
Hey @matt-snider good job, 

I am a bit lazy to look up how to use your tool with language here on github like:
`dict-cc --from es --to de diccionario`  
so could you add this to the help/info output on the commandline?

Thx

**Comment by matt-snider** [comment]
Hi @zykoq thanks for opening this issue.

I added `--help`:
```
$ dict-cc --help
Usage: dict.cc [OPTION...] word

  -f FROM   --from=FROM    language to translate from
  -t TO     --to=TO        language to translate to
  -l LIMIT  --limit=LIMIT  limit the number of results
  -r        --reverse      reverse the default from & to
  -n        --noun         only return results that are nouns
  -v        --verb         only return results that are verbs
  -h        --help         show this help text
  -V        --version      show the version
``` 

Is this what you were looking for or did you mean you think it would be good to have an example in the --help output?

**Comment by zykoq** [comment]
Yes, "spitzengemäß"
